function analyze_spatial_sweep(sweepTable)
%ANALYZE_SPATIAL_SWEEP Plot the spatial sweep results.
%
% The function expects a table generated by run_spatial_sweep. Error bars are
% one standard deviation across independent stochastic replicates.

if nargin < 1 || isempty(sweepTable)
    sweepTable = run_spatial_sweep(30, {'diffusion','taxis'});
end

sigmaValues = unique(sweepTable.sigmaLevel);
modes = {'diffusion','taxis'};

for i = 1:numel(sigmaValues)
    sigmaValue = sigmaValues(i);
    sigmaLabel = strrep(sprintf('%0.2f', sigmaValue), '.', 'p');

    % ---------------------------------------------------------------------
    % Final mean gut fullness
    % ---------------------------------------------------------------------
    figure('Color','w'); hold on;
    for m = 1:numel(modes)
        mode = modes{m};
        idx = sweepTable.sigmaLevel == sigmaValue & strcmp(sweepTable.mode, mode);
        T = sortrows(sweepTable(idx,:), 'Hscale');
        errorbar(T.Hscale, T.meanGFinal_mean, T.meanGFinal_std, '-o', ...
            'LineWidth', 1.8, 'MarkerSize', 6);
    end
    grid on; box on;
    xlabel('Heterogeneidad espacial, H_{scale}');
    ylabel('Llenado digestivo medio final, G');
    ylim([0.56 0.74]);
    title(sprintf('Barrido de llenado digestivo, sigma = %0.2f', sigmaValue));
    legend({'difusión','taxis'}, 'Location', 'best');
    save_current_figure(sprintf('fig_sweep_mean_g_sigma_%s', sigmaLabel));

    % ---------------------------------------------------------------------
    % Final patch occupancy
    % ---------------------------------------------------------------------
    figure('Color','w'); hold on;
    for m = 1:numel(modes)
        mode = modes{m};
        idx = sweepTable.sigmaLevel == sigmaValue & strcmp(sweepTable.mode, mode);
        T = sortrows(sweepTable(idx,:), 'Hscale');
        errorbar(T.Hscale, T.patchFractionFinal_mean, T.patchFractionFinal_std, '-o', ...
            'LineWidth', 1.8, 'MarkerSize', 6);
    end
    grid on; box on;
    xlabel('Heterogeneidad espacial, H_{scale}');
    ylabel('Fracción final dentro del parche');
    ylim([0.04 0.52]);
    title(sprintf('Barrido de ocupación del parche, sigma = %0.2f', sigmaValue));
    legend({'difusión','taxis'}, 'Location', 'best');
    save_current_figure(sprintf('fig_sweep_patch_fraction_sigma_%s', sigmaLabel));
end

end
